### ISSUE TITLE
Text Buffer class

### ISSUE THREAD

**Issue by russleyshaw** [kwiwk/editor#12]
This class is responsible for storing loaded text

The class should provide the means to:
- [x] initialize a blank/empty buffer - aka empty
- [x] load a file from the file system given a path - aka load
- [x] save a previously loaded file as the same name it was loaded - aka save
- [x] save a text buffer as a file under a different name and location - aka save as
- [ ] contain a stubbed draw function

The class should contain the following data at a minimum:
- [x] the loaded text as an array of strings(lines)
- [x] the x coordinate for the buffer to be drawn, where x=0 means far left
- [x] the y coordinate for the buffer to be drawn, where x=0 means top
- [x] a width, how wide can the text buffer be drawn
- [x] a height, how high can the text buffer be drawn
- [x] an active boolean, if false, do not draw, if true, draw

**Comment by russleyshaw** [comment]
@MReidBlack I haven't seen any code pushed for this simple issue, so I'm assigning over to @IanTClark so he can actual ncurses drawing/file loading

**Comment by alzk6** [comment]
ANSI codes:
http://bluesock.org/~willg/dev/ansi.html

underline,bold,colors(will add more if time allows)
uint16 = (foreground<4>,background<4>,bold,underline) rest will work out 

attr |= underline)bit

const uint16 underline_bit = 0x0004 for underline
const uint16 bold_bit = 0x0001 for bold

**Comment by alzk6** [comment]
add scroll location

**Comment by IanTClark** [comment]
call on_load, on_update, on_draw functions in the plugin manager, pass a this pointer, as appropriate.
maybe rename local functions?
text buffer should have a function for every instance where it is needed (load, update, draw) to call the plugin manager, that function does the actual call to the plugin manager.

**Comment by russleyshaw** [comment]
Closing, main drawing finished
