### ISSUE TITLE
Kwiwk Application class

### ISSUE THREAD

**Issue by russleyshaw** [kwiwk/editor#13]
There should be a root level application that provides entry into our application. It should contain functions that will help us.

The Kwiwk application class should provide the methods to:
- [ ] initialize a ncurses session
- [ ] get the terminal width
- [ ] get the terminal height
- [ ] a stubbed out run function that will contain the main loop of our application

The Kwiwk application should contain at minimum the following data:
- [ ] a boolean `quit` that is initialized to false.

**Comment by IanTClark** [comment]
I pushed what I have for the initial application and file pane classes to the master branch.  I do not have any headers associated yet.  What do I need to do for those?

**Comment by russleyshaw** [comment]
You will need to do similar for what you've done for C++ the entire CS career and put your class declarations into a `.h` or in our case, a `.hpp` file in the `include/kwiwk` folder

**Comment by IanTClark** [comment]
Alright, I think I got the header files done correctly.  As far as I can find, getmaxyx() returns the number of rows and columns in the current window.

**Comment by russleyshaw** [comment]
Next link up the file pane in #14 and the kwiwk_application so that the file pane is loaded when the kwiwk app is

**Comment by russleyshaw** [comment]
@IanTClark please update the Application class to be able to be constructable with:

- [ ] `Application(string[])` - given array of files
- [ ] `Application(string, string[])` - given folder and array of files

**Comment by russleyshaw** [comment]
Initial development complete
