### ISSUE TITLE
Program Options

### ISSUE THREAD

**Issue by russleyshaw** [kwiwk/editor#16]
http://www.boost.org/doc/libs/1_56_0/doc/html/program_options/tutorial.html

- [ ] Accept multiple files
- [ ] Accept a single folder
- [x] `--version`
- [x] `--help`

**Comment by russleyshaw** [comment]
Files and folder should be passed into the Application class's constructor

`Application(files)` if folder not provided
`Application(folder, files)` if folder provided

**Comment by russleyshaw** [comment]
@2ajoyce is this done?

**Comment by 2ajoyce** [comment]
Yes, I think it is. The branch still isn't building properly, but I think I got all the bugs with boost filetypes sorted out.
