### ISSUE TITLE
Add .gitattributes

### ISSUE THREAD

**Issue by russleyshaw** [kwiwk/editor#19]
When using vagrant, its possible to commit Windows line endings (because only git bash converts things back to unix line endings, but vagrant's git pushes it as is. 

By including a `.gitattributes` file with a special setting, I believe we can prevent people from pushing Windows line endings to our Linux product. 

https://help.github.com/articles/dealing-with-line-endings/

**Comment by 2ajoyce** [comment]
Created pull request for a branch that implements a solution to this problem.
